#:schema node_modules/wrangler/config-schema.json
name = "anchor"
compatibility_date = "2025-01-04"
compatibility_flags = ["nodejs_compat"]

# SPA Static Assets - Routes all 404s to index.html for client-side routing
[assets]
directory = "dist"

# Development Environment
[env.dev]
name = "anchor-dev"

[env.dev.vars]
ENVIRONMENT = "dev"
VITE_API_URL = "https://anchor-dev-api.erniesg.workers.dev"

# Production Environment
[env.production]
name = "anchor"

[env.production.vars]
ENVIRONMENT = "production"
VITE_API_URL = "https://anchor-api.erniesg.workers.dev"
