/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyTrendsRouteImport } from './routes/family/trends'
import { Route as FamilyDashboardRouteImport } from './routes/family/dashboard'
import { Route as CaregiverPackListRouteImport } from './routes/caregiver/pack-list'
import { Route as CaregiverLoginRouteImport } from './routes/caregiver/login'
import { Route as CaregiverFormLegacyRouteImport } from './routes/caregiver/form-legacy'
import { Route as CaregiverFormRouteImport } from './routes/caregiver/form'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as FamilySettingsIndexRouteImport } from './routes/family/settings/index'
import { Route as FamilyOnboardingIndexRouteImport } from './routes/family/onboarding/index'
import { Route as CaregiverFormIndexRouteImport } from './routes/caregiver/form/index'
import { Route as FamilySettingsProfileRouteImport } from './routes/family/settings/profile'
import { Route as FamilySettingsPackListRouteImport } from './routes/family/settings/pack-list'
import { Route as FamilySettingsFamilyMembersRouteImport } from './routes/family/settings/family-members'
import { Route as FamilySettingsCaregiversRouteImport } from './routes/family/settings/caregivers'
import { Route as FamilySettingsCareRecipientsRouteImport } from './routes/family/settings/care-recipients'
import { Route as FamilyOnboardingCaregiverRouteImport } from './routes/family/onboarding/caregiver'
import { Route as CaregiverFormSummaryRouteImport } from './routes/caregiver/form/summary'
import { Route as CaregiverFormMorningRouteImport } from './routes/caregiver/form/morning'
import { Route as CaregiverFormEveningRouteImport } from './routes/caregiver/form/evening'
import { Route as CaregiverFormAfternoonRouteImport } from './routes/caregiver/form/afternoon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTrendsRoute = FamilyTrendsRouteImport.update({
  id: '/family/trends',
  path: '/family/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDashboardRoute = FamilyDashboardRouteImport.update({
  id: '/family/dashboard',
  path: '/family/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverPackListRoute = CaregiverPackListRouteImport.update({
  id: '/caregiver/pack-list',
  path: '/caregiver/pack-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverLoginRoute = CaregiverLoginRouteImport.update({
  id: '/caregiver/login',
  path: '/caregiver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverFormLegacyRoute = CaregiverFormLegacyRouteImport.update({
  id: '/caregiver/form-legacy',
  path: '/caregiver/form-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverFormRoute = CaregiverFormRouteImport.update({
  id: '/caregiver/form',
  path: '/caregiver/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilySettingsIndexRoute = FamilySettingsIndexRouteImport.update({
  id: '/family/settings/',
  path: '/family/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyOnboardingIndexRoute = FamilyOnboardingIndexRouteImport.update({
  id: '/family/onboarding/',
  path: '/family/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverFormIndexRoute = CaregiverFormIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaregiverFormRoute,
} as any)
const FamilySettingsProfileRoute = FamilySettingsProfileRouteImport.update({
  id: '/family/settings/profile',
  path: '/family/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilySettingsPackListRoute = FamilySettingsPackListRouteImport.update({
  id: '/family/settings/pack-list',
  path: '/family/settings/pack-list',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilySettingsFamilyMembersRoute =
  FamilySettingsFamilyMembersRouteImport.update({
    id: '/family/settings/family-members',
    path: '/family/settings/family-members',
    getParentRoute: () => rootRouteImport,
  } as any)
const FamilySettingsCaregiversRoute =
  FamilySettingsCaregiversRouteImport.update({
    id: '/family/settings/caregivers',
    path: '/family/settings/caregivers',
    getParentRoute: () => rootRouteImport,
  } as any)
const FamilySettingsCareRecipientsRoute =
  FamilySettingsCareRecipientsRouteImport.update({
    id: '/family/settings/care-recipients',
    path: '/family/settings/care-recipients',
    getParentRoute: () => rootRouteImport,
  } as any)
const FamilyOnboardingCaregiverRoute =
  FamilyOnboardingCaregiverRouteImport.update({
    id: '/family/onboarding/caregiver',
    path: '/family/onboarding/caregiver',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaregiverFormSummaryRoute = CaregiverFormSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => CaregiverFormRoute,
} as any)
const CaregiverFormMorningRoute = CaregiverFormMorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => CaregiverFormRoute,
} as any)
const CaregiverFormEveningRoute = CaregiverFormEveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => CaregiverFormRoute,
} as any)
const CaregiverFormAfternoonRoute = CaregiverFormAfternoonRouteImport.update({
  id: '/afternoon',
  path: '/afternoon',
  getParentRoute: () => CaregiverFormRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/caregiver/form': typeof CaregiverFormRouteWithChildren
  '/caregiver/form-legacy': typeof CaregiverFormLegacyRoute
  '/caregiver/login': typeof CaregiverLoginRoute
  '/caregiver/pack-list': typeof CaregiverPackListRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/trends': typeof FamilyTrendsRoute
  '/caregiver/form/afternoon': typeof CaregiverFormAfternoonRoute
  '/caregiver/form/evening': typeof CaregiverFormEveningRoute
  '/caregiver/form/morning': typeof CaregiverFormMorningRoute
  '/caregiver/form/summary': typeof CaregiverFormSummaryRoute
  '/family/onboarding/caregiver': typeof FamilyOnboardingCaregiverRoute
  '/family/settings/care-recipients': typeof FamilySettingsCareRecipientsRoute
  '/family/settings/caregivers': typeof FamilySettingsCaregiversRoute
  '/family/settings/family-members': typeof FamilySettingsFamilyMembersRoute
  '/family/settings/pack-list': typeof FamilySettingsPackListRoute
  '/family/settings/profile': typeof FamilySettingsProfileRoute
  '/caregiver/form/': typeof CaregiverFormIndexRoute
  '/family/onboarding': typeof FamilyOnboardingIndexRoute
  '/family/settings': typeof FamilySettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/caregiver/form-legacy': typeof CaregiverFormLegacyRoute
  '/caregiver/login': typeof CaregiverLoginRoute
  '/caregiver/pack-list': typeof CaregiverPackListRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/trends': typeof FamilyTrendsRoute
  '/caregiver/form/afternoon': typeof CaregiverFormAfternoonRoute
  '/caregiver/form/evening': typeof CaregiverFormEveningRoute
  '/caregiver/form/morning': typeof CaregiverFormMorningRoute
  '/caregiver/form/summary': typeof CaregiverFormSummaryRoute
  '/family/onboarding/caregiver': typeof FamilyOnboardingCaregiverRoute
  '/family/settings/care-recipients': typeof FamilySettingsCareRecipientsRoute
  '/family/settings/caregivers': typeof FamilySettingsCaregiversRoute
  '/family/settings/family-members': typeof FamilySettingsFamilyMembersRoute
  '/family/settings/pack-list': typeof FamilySettingsPackListRoute
  '/family/settings/profile': typeof FamilySettingsProfileRoute
  '/caregiver/form': typeof CaregiverFormIndexRoute
  '/family/onboarding': typeof FamilyOnboardingIndexRoute
  '/family/settings': typeof FamilySettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/caregiver/form': typeof CaregiverFormRouteWithChildren
  '/caregiver/form-legacy': typeof CaregiverFormLegacyRoute
  '/caregiver/login': typeof CaregiverLoginRoute
  '/caregiver/pack-list': typeof CaregiverPackListRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/trends': typeof FamilyTrendsRoute
  '/caregiver/form/afternoon': typeof CaregiverFormAfternoonRoute
  '/caregiver/form/evening': typeof CaregiverFormEveningRoute
  '/caregiver/form/morning': typeof CaregiverFormMorningRoute
  '/caregiver/form/summary': typeof CaregiverFormSummaryRoute
  '/family/onboarding/caregiver': typeof FamilyOnboardingCaregiverRoute
  '/family/settings/care-recipients': typeof FamilySettingsCareRecipientsRoute
  '/family/settings/caregivers': typeof FamilySettingsCaregiversRoute
  '/family/settings/family-members': typeof FamilySettingsFamilyMembersRoute
  '/family/settings/pack-list': typeof FamilySettingsPackListRoute
  '/family/settings/profile': typeof FamilySettingsProfileRoute
  '/caregiver/form/': typeof CaregiverFormIndexRoute
  '/family/onboarding/': typeof FamilyOnboardingIndexRoute
  '/family/settings/': typeof FamilySettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/caregiver/form'
    | '/caregiver/form-legacy'
    | '/caregiver/login'
    | '/caregiver/pack-list'
    | '/family/dashboard'
    | '/family/trends'
    | '/caregiver/form/afternoon'
    | '/caregiver/form/evening'
    | '/caregiver/form/morning'
    | '/caregiver/form/summary'
    | '/family/onboarding/caregiver'
    | '/family/settings/care-recipients'
    | '/family/settings/caregivers'
    | '/family/settings/family-members'
    | '/family/settings/pack-list'
    | '/family/settings/profile'
    | '/caregiver/form/'
    | '/family/onboarding'
    | '/family/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/caregiver/form-legacy'
    | '/caregiver/login'
    | '/caregiver/pack-list'
    | '/family/dashboard'
    | '/family/trends'
    | '/caregiver/form/afternoon'
    | '/caregiver/form/evening'
    | '/caregiver/form/morning'
    | '/caregiver/form/summary'
    | '/family/onboarding/caregiver'
    | '/family/settings/care-recipients'
    | '/family/settings/caregivers'
    | '/family/settings/family-members'
    | '/family/settings/pack-list'
    | '/family/settings/profile'
    | '/caregiver/form'
    | '/family/onboarding'
    | '/family/settings'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/caregiver/form'
    | '/caregiver/form-legacy'
    | '/caregiver/login'
    | '/caregiver/pack-list'
    | '/family/dashboard'
    | '/family/trends'
    | '/caregiver/form/afternoon'
    | '/caregiver/form/evening'
    | '/caregiver/form/morning'
    | '/caregiver/form/summary'
    | '/family/onboarding/caregiver'
    | '/family/settings/care-recipients'
    | '/family/settings/caregivers'
    | '/family/settings/family-members'
    | '/family/settings/pack-list'
    | '/family/settings/profile'
    | '/caregiver/form/'
    | '/family/onboarding/'
    | '/family/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CaregiverFormRoute: typeof CaregiverFormRouteWithChildren
  CaregiverFormLegacyRoute: typeof CaregiverFormLegacyRoute
  CaregiverLoginRoute: typeof CaregiverLoginRoute
  CaregiverPackListRoute: typeof CaregiverPackListRoute
  FamilyDashboardRoute: typeof FamilyDashboardRoute
  FamilyTrendsRoute: typeof FamilyTrendsRoute
  FamilyOnboardingCaregiverRoute: typeof FamilyOnboardingCaregiverRoute
  FamilySettingsCareRecipientsRoute: typeof FamilySettingsCareRecipientsRoute
  FamilySettingsCaregiversRoute: typeof FamilySettingsCaregiversRoute
  FamilySettingsFamilyMembersRoute: typeof FamilySettingsFamilyMembersRoute
  FamilySettingsPackListRoute: typeof FamilySettingsPackListRoute
  FamilySettingsProfileRoute: typeof FamilySettingsProfileRoute
  FamilyOnboardingIndexRoute: typeof FamilyOnboardingIndexRoute
  FamilySettingsIndexRoute: typeof FamilySettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/trends': {
      id: '/family/trends'
      path: '/family/trends'
      fullPath: '/family/trends'
      preLoaderRoute: typeof FamilyTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/dashboard': {
      id: '/family/dashboard'
      path: '/family/dashboard'
      fullPath: '/family/dashboard'
      preLoaderRoute: typeof FamilyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/pack-list': {
      id: '/caregiver/pack-list'
      path: '/caregiver/pack-list'
      fullPath: '/caregiver/pack-list'
      preLoaderRoute: typeof CaregiverPackListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/login': {
      id: '/caregiver/login'
      path: '/caregiver/login'
      fullPath: '/caregiver/login'
      preLoaderRoute: typeof CaregiverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/form-legacy': {
      id: '/caregiver/form-legacy'
      path: '/caregiver/form-legacy'
      fullPath: '/caregiver/form-legacy'
      preLoaderRoute: typeof CaregiverFormLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/form': {
      id: '/caregiver/form'
      path: '/caregiver/form'
      fullPath: '/caregiver/form'
      preLoaderRoute: typeof CaregiverFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/settings/': {
      id: '/family/settings/'
      path: '/family/settings'
      fullPath: '/family/settings'
      preLoaderRoute: typeof FamilySettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/onboarding/': {
      id: '/family/onboarding/'
      path: '/family/onboarding'
      fullPath: '/family/onboarding'
      preLoaderRoute: typeof FamilyOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/form/': {
      id: '/caregiver/form/'
      path: '/'
      fullPath: '/caregiver/form/'
      preLoaderRoute: typeof CaregiverFormIndexRouteImport
      parentRoute: typeof CaregiverFormRoute
    }
    '/family/settings/profile': {
      id: '/family/settings/profile'
      path: '/family/settings/profile'
      fullPath: '/family/settings/profile'
      preLoaderRoute: typeof FamilySettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/settings/pack-list': {
      id: '/family/settings/pack-list'
      path: '/family/settings/pack-list'
      fullPath: '/family/settings/pack-list'
      preLoaderRoute: typeof FamilySettingsPackListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/settings/family-members': {
      id: '/family/settings/family-members'
      path: '/family/settings/family-members'
      fullPath: '/family/settings/family-members'
      preLoaderRoute: typeof FamilySettingsFamilyMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/settings/caregivers': {
      id: '/family/settings/caregivers'
      path: '/family/settings/caregivers'
      fullPath: '/family/settings/caregivers'
      preLoaderRoute: typeof FamilySettingsCaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/settings/care-recipients': {
      id: '/family/settings/care-recipients'
      path: '/family/settings/care-recipients'
      fullPath: '/family/settings/care-recipients'
      preLoaderRoute: typeof FamilySettingsCareRecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/onboarding/caregiver': {
      id: '/family/onboarding/caregiver'
      path: '/family/onboarding/caregiver'
      fullPath: '/family/onboarding/caregiver'
      preLoaderRoute: typeof FamilyOnboardingCaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/form/summary': {
      id: '/caregiver/form/summary'
      path: '/summary'
      fullPath: '/caregiver/form/summary'
      preLoaderRoute: typeof CaregiverFormSummaryRouteImport
      parentRoute: typeof CaregiverFormRoute
    }
    '/caregiver/form/morning': {
      id: '/caregiver/form/morning'
      path: '/morning'
      fullPath: '/caregiver/form/morning'
      preLoaderRoute: typeof CaregiverFormMorningRouteImport
      parentRoute: typeof CaregiverFormRoute
    }
    '/caregiver/form/evening': {
      id: '/caregiver/form/evening'
      path: '/evening'
      fullPath: '/caregiver/form/evening'
      preLoaderRoute: typeof CaregiverFormEveningRouteImport
      parentRoute: typeof CaregiverFormRoute
    }
    '/caregiver/form/afternoon': {
      id: '/caregiver/form/afternoon'
      path: '/afternoon'
      fullPath: '/caregiver/form/afternoon'
      preLoaderRoute: typeof CaregiverFormAfternoonRouteImport
      parentRoute: typeof CaregiverFormRoute
    }
  }
}

interface CaregiverFormRouteChildren {
  CaregiverFormAfternoonRoute: typeof CaregiverFormAfternoonRoute
  CaregiverFormEveningRoute: typeof CaregiverFormEveningRoute
  CaregiverFormMorningRoute: typeof CaregiverFormMorningRoute
  CaregiverFormSummaryRoute: typeof CaregiverFormSummaryRoute
  CaregiverFormIndexRoute: typeof CaregiverFormIndexRoute
}

const CaregiverFormRouteChildren: CaregiverFormRouteChildren = {
  CaregiverFormAfternoonRoute: CaregiverFormAfternoonRoute,
  CaregiverFormEveningRoute: CaregiverFormEveningRoute,
  CaregiverFormMorningRoute: CaregiverFormMorningRoute,
  CaregiverFormSummaryRoute: CaregiverFormSummaryRoute,
  CaregiverFormIndexRoute: CaregiverFormIndexRoute,
}

const CaregiverFormRouteWithChildren = CaregiverFormRoute._addFileChildren(
  CaregiverFormRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CaregiverFormRoute: CaregiverFormRouteWithChildren,
  CaregiverFormLegacyRoute: CaregiverFormLegacyRoute,
  CaregiverLoginRoute: CaregiverLoginRoute,
  CaregiverPackListRoute: CaregiverPackListRoute,
  FamilyDashboardRoute: FamilyDashboardRoute,
  FamilyTrendsRoute: FamilyTrendsRoute,
  FamilyOnboardingCaregiverRoute: FamilyOnboardingCaregiverRoute,
  FamilySettingsCareRecipientsRoute: FamilySettingsCareRecipientsRoute,
  FamilySettingsCaregiversRoute: FamilySettingsCaregiversRoute,
  FamilySettingsFamilyMembersRoute: FamilySettingsFamilyMembersRoute,
  FamilySettingsPackListRoute: FamilySettingsPackListRoute,
  FamilySettingsProfileRoute: FamilySettingsProfileRoute,
  FamilyOnboardingIndexRoute: FamilyOnboardingIndexRoute,
  FamilySettingsIndexRoute: FamilySettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
