/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyDashboardRouteImport } from './routes/family/dashboard'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as FamilyOnboardingIndexRouteImport } from './routes/family/onboarding/index'
import { Route as FamilyOnboardingCaregiverRouteImport } from './routes/family/onboarding/caregiver'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDashboardRoute = FamilyDashboardRouteImport.update({
  id: '/family/dashboard',
  path: '/family/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyOnboardingIndexRoute = FamilyOnboardingIndexRouteImport.update({
  id: '/family/onboarding/',
  path: '/family/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyOnboardingCaregiverRoute =
  FamilyOnboardingCaregiverRouteImport.update({
    id: '/family/onboarding/caregiver',
    path: '/family/onboarding/caregiver',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/onboarding/caregiver': typeof FamilyOnboardingCaregiverRoute
  '/family/onboarding': typeof FamilyOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/onboarding/caregiver': typeof FamilyOnboardingCaregiverRoute
  '/family/onboarding': typeof FamilyOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/onboarding/caregiver': typeof FamilyOnboardingCaregiverRoute
  '/family/onboarding/': typeof FamilyOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/family/dashboard'
    | '/family/onboarding/caregiver'
    | '/family/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/family/dashboard'
    | '/family/onboarding/caregiver'
    | '/family/onboarding'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/family/dashboard'
    | '/family/onboarding/caregiver'
    | '/family/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  FamilyDashboardRoute: typeof FamilyDashboardRoute
  FamilyOnboardingCaregiverRoute: typeof FamilyOnboardingCaregiverRoute
  FamilyOnboardingIndexRoute: typeof FamilyOnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/dashboard': {
      id: '/family/dashboard'
      path: '/family/dashboard'
      fullPath: '/family/dashboard'
      preLoaderRoute: typeof FamilyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/onboarding/': {
      id: '/family/onboarding/'
      path: '/family/onboarding'
      fullPath: '/family/onboarding'
      preLoaderRoute: typeof FamilyOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/onboarding/caregiver': {
      id: '/family/onboarding/caregiver'
      path: '/family/onboarding/caregiver'
      fullPath: '/family/onboarding/caregiver'
      preLoaderRoute: typeof FamilyOnboardingCaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  FamilyDashboardRoute: FamilyDashboardRoute,
  FamilyOnboardingCaregiverRoute: FamilyOnboardingCaregiverRoute,
  FamilyOnboardingIndexRoute: FamilyOnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
