name = "anchor-dev-api"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

vars = { ENVIRONMENT = "dev" }

[[d1_databases]]
binding = "DB"
database_name = "anchor-dev-db"
database_id = ""
migrations_dir = "../../packages/database/drizzle/migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "anchor-dev-storage"

[dev]
port = 8787

[miniflare]
d1_persist = true
