# Anchor API - Cloudflare Workers Configuration

name = "anchor-api"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Development Environment
[env.dev]
name = "anchor-dev-api"
vars = { ENVIRONMENT = "dev" }

[[env.dev.d1_databases]]
binding = "DB"
database_name = "anchor-dev-db"
database_id = "900612ba-b5f7-4593-ac31-8bb9abac2c11"
migrations_dir = "../../packages/database/drizzle/migrations"

[[env.dev.r2_buckets]]
binding = "STORAGE"
bucket_name = "anchor-dev-storage"

# Production Environment
[env.production]
name = "anchor-prod-api"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "anchor-prod-db"
database_id = "df69ea4c-71f6-45db-bd47-3f1e3f3bdaee"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "anchor-prod-storage"

# Secrets (set via wrangler secret put)
# - JWT_SECRET
# - LOGTO_APP_SECRET