# Anchor API - Cloudflare Workers Configuration

name = "anchor-api"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Development Environment
[env.dev]
name = "anchor-dev-api"
vars = { ENVIRONMENT = "dev" }

[[env.dev.d1_databases]]
binding = "DB"
database_name = "anchor-dev-db"
database_id = "" # Auto-filled by setup-cloudflare.js

[[env.dev.r2_buckets]]
binding = "STORAGE"
bucket_name = "anchor-dev-storage"

# Production Environment
[env.production]
name = "anchor-prod-api"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "anchor-prod-db"
database_id = "" # Auto-filled by setup-cloudflare.js

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "anchor-prod-storage"

# Secrets (set via wrangler secret put)
# - JWT_SECRET
# - LOGTO_APP_SECRET